# -*- coding: utf-8 -*-
"""10/9: Moodle Assignment 3: Fortune Teller

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qf0uH5zYP51cBQuxWr8PWjjztkgRqEtc
"""

#Fortune Teller's introduction
print("I am a fortune teller. I will ask you questions. Your answer will determine your fortune. Let us begin...")

# Counter to keep track of the number of times the loop has run
counter = 0

while counter < 2:  # Run the loop twice
    print('Tell me a whole number between 1 and 8')

    user_input = float(input())
    try:

      #Error Message
      if user_input <=0 or user_input > 8:
        print('Zero, all negative numbers, decimals between 1-8, and any number above 8 will not give you a fortune. Please try again!')

      #Fortune 1
      if user_input == 1:
        print('You will find great success in your future endeavors, as long as you remember to wear matching socks. Mismatched socks bring chaos')

      #Fortune 2
      if user_input == 2:
        print('An unexpected gift will soon come your way. It might be a fruitcake from Aunt Mildred. Brace yourself!')

      #Fortune 3
      if user_input == 3:
        print("Your sense of humor will be your greatest asset. Just remember, a good laugh is like a mini-vacation, but don't forget to come back from this trip")

      #Fortune 4
      if user_input == 4:
        print('Beware of ducks. They may seem innocent, but they are secretly plotting to steal your snacks')

      #Fortune 5
      if user_input == 5:
        print('A wise person once said: A balanced diet means a cookie in each hand. Follow this wisdom, and you will find happiness')

      #Fortune 6
      if user_input == 6:
        print('You are destined to meet someone who will change your life. They might also change your Netflix password, so be cautious')

      #Fortune 7
      if user_input == 7:
        print("Good fortune awaits you at the intersection of determination and imagination. Just make sure you don't take a wrong turn at procrastination")

      #Fortune 8
      if user_input == 8:
        print("Remember, life is like a roller coaster – sometimes you're up, sometimes you're down, and sometimes you just want to scream ""I want off!""")

      counter += 1 #Counter Increment

      if counter == 2: #Break the loop after running twice
        break

    except False:
      print('Invalid response: Please try again!')