# -*- coding: utf-8 -*-
"""9/25_Moodle_Assignment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UtPSzxMDkowNKKrdymINxea7bREfBSVC
"""

from pickle import NONE
#Task2:

#Item1 Input
print('What food item was purchased?:')
food = input()
print('What did the item cost (in $)?:')
food_cost = float(input())
print('How many were bought?')
food_quantity = float(input())

food_cost_total = food_quantity * food_cost
#Gratuity Calculation + Food Cost

food_tip = (food_cost_total * .15)
print(f'{food_tip:.2f}')
food_total = food_cost_total + food_tip

#Receipt
print('RECEIPT:')
print(food_quantity, food, 'costs a total of', food_cost_total)
print("")
print('15% tip/gratuity is:', f'{food_tip:.2f}')
print('Total with tip (in $):', f'{food_total:.2f}')
print("")

#Item2 Input
print('Enter a second item:')
print('What food item was purchased?:')
food2 = input()
print('What did the item cost (in $)?:')
food_cost2 = float(input())
print('How many were bought?')
food_quantity2 = float(input())

food_cost_total2 = food_quantity2 * food_cost2

#Gratuity Calculation + Food Cost
food_tip2 = (food_cost_total2 * .15)
food_total2 = food_cost_total2 + food_tip2

#Receipt
print('RECEIPT:')
print(food_quantity2, food2, 'costs a total of', food_cost_total2)
print("")
print('15% gratuity:', f'{food_tip2:.2f}')
print('Total with tip (in $):', f'{food_total2:.2f}')