# -*- coding: utf-8 -*-
"""Moodle Assignment 2: 10/2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10zUS-5itg5IgLod9CGXdCbRnNNcTnwWQ
"""

from typing_extensions import NamedTuple
#Task 1
#Food Dictionary Creation
food_dictionary = {
    'Banana': .02,
    'Chicken Breast': 4.35,
    'Spaghetti Pasta': 12.50,
    'Canned Tomato Sauce': 1.35,
    'Greek Yogurt': 1.25,
    #Step 3
    input(): float(input()),
    input(): float(input())
}
# Step 2
print("The Food Dictionary:", food_dictionary)

#Dictionary to list conversion

food_list = list(food_dictionary.keys())
price_list = list(food_dictionary.values())

#Price_List_Average Calculation

total_prices_average = sum(price_list) / len(price_list)
print('Average price per food item:', total_prices_average)

#Task 2

#Item 1
print("Item Price Check")
if price_list[1] < 1:
  print('The following item', food_list[1], ', is cheap')
elif (price_list[1] < 10 and price_list[1] > 1):
  print('The following item,', food_list[1], ', is normally priced')
elif (price_list[1] > 10):
  print('The following item,', food_list[1], ', is expensive')

#Item 2
if price_list[3] < 1:
  print('The following item', food_list[3], ', is cheap')
elif (price_list[3] < 10 and price_list[3] > 1):
  print('The following item,', food_list[3], ', is normally priced')
elif (price_list[3] > 10):
  print('The following item,', food_list[3], ', is expensive')

#Item 3
if price_list[5] < 1:
  print('The following item', food_list[5], ', is cheap')
elif (price_list[5] < 10 and price_list[5] > 1):
  print('The following item,', food_list[5], ', is normally priced')
elif (price_list[5] > 10):
  print('The following item,', food_list[5], ', is expensive')